name: Coverage report

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [master, main]
jobs:
  coverage:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_commit.id }}
      - name: Download Coverage Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          commit: ${{ github.event.workflow_run.head_commit.id }}
          name: test-report
          path: test-report
      - name: Produce Coverage report
        uses: ./
        with:
          path: test-report/report.xml
          minimum_coverage: 70
          fail_below_threshold: false